### ISSUE TITLE
It didn't work when I use "flarum-cli make frontend model"

### ISSUE THREAD

**Issue by JOU-amjs** [flarum/cli#23]
![image](https://user-images.githubusercontent.com/29848971/146555630-17f3b51a-773e-411c-a65d-5e1952074797.png)

I got two problems when I use @flarum/cli
1. It didn't work when I write "flarum-cli make frontend model"
2. It occurred a error, see the snapshot. It also happened when I use "flarum-cli -v"、"flarum-cli init xxx" and so on.

**Comment by SychO9** [comment]
looks like the cli didn't properly install, try reinstalling it
