### ISSUE TITLE
npm install -g @flarum/cli 安装时出错。

### ISSUE THREAD

**Issue by jiangjiali** [flarum/cli#39]
![image](https://github.com/flarum/cli/assets/7267234/0e49cb1d-b920-42c6-9655-e1d2e413d1cb)

**Comment by davwheat** [comment]
There's no error in your screenshot.

**Comment by jiangjiali** [comment]
![image](https://github.com/flarum/cli/assets/7267234/47e8e07e-0ba0-4f66-805b-a1411118e987)
这个是什么什么问题呢？

**Comment by jiangjiali** [comment]
> There's no error in your screenshot.

感谢你的回答。

**Comment by luceos** [comment]
Seems that your php version might be too old @jiangjiali . 

Please use a translator or something to communicate with us moving forward.

**Comment by jiangjiali** [comment]
> Seems that your php version might be too old @jiangjiali .
> 
> Please use a translator or something to communicate with us moving forward.


I have found the reason.
Due to a symbol error in the code.

**Comment by jiangjiali** [comment]
> Seems that your php version might be too old @jiangjiali .
> 
> Please use a translator or something to communicate with us moving forward.

Thank you very much for your answer.
