### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by 13693156733** [flarum/cli#40]
I apologize if they might seem foolish. I'm just a beginner who is learning.
`flarum-cli init ksluntan.top

     _-----_     ╭──────────────────────────╮
    |       |    │    Welcome to a Flarum   │
    |--(o)--|    │    extension generator   │
   `---------´   │                          │
    ( _´U`_ )    │       - Flarum Team      │
    /___A___\   /╰──────────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

✔ Directory not empty. Overwrite? … yes
✔ Run `git init`? (recommended) … yes
✔ Package (vendor/extension-name) … vendor/Myobject
✔ Package description … something should be used for a anime doujin forum
✔ Package namespace (Vendor\ExtensionName) … Vendor\useing
✔ Author name … Dooooove
✔ Author email … 3156522837@qq.com
✔ Extension name … Dooooove
✔ License › MIT 
✔ Main git branch (JS will automatically build when changes are pushed to GitHub on this branch) … flarum
✔ JS Package Manager › Yarn
✔ Advanced Initialization (fine-tune which features are enabled) … yes
✔ Admin Frontend … yes
✔ Forum Frontend … yes
✔ Javascript (Files, tools, and scripts to build Flarum's frontend.) … yes
✔ JS common code (Shared code between the forum and the admin frontends) … yes
✔ CSS (LESS starter files for Flarum's frontend styling.) … yes
✔ Locale (Translation starter files.) … yes
✔ Git Configuration (Git config files (e.g. .gitignore, .gitattributes).) … yes
✔ GitHub Actions CI (Automatically run checks via GitHub Actions CI. Free for open source projects.) … yes
✔ Auto-format frontend code with Prettier. … yes
✔ Support TypeScript in frontend code. … yes
✔ Enable Bundlewatch Checks … yes
✔ Backend PHP unit and integration testing via PHPUnit. … yes
✔ EditorConfig setup … yes
✔ StyleCI config file … yes
✔ Run `composer install`? (recommended) … yes
Composer plugins have been disabled for safety in this non-interactive session. Set COMPOSER_ALLOW_SUPERUSER=1 if you want to allow plugins to run as root/super user.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Lock file operations: 150 installs, 0 updates, 0 removals
  - Locking axy/backtrace (2.0.0)
  - Locking brick/math (0.11.0)
  - Locking carbonphp/carbon-doctrine-types (1.0.0)
  - Locking components/font-awesome (5.15.4)
  - Locking dflydev/dot-access-data (v3.0.2)
  - Locking dflydev/fig-cookies (v3.1.0)
  - Locking doctrine/cache (2.2.0)
  - Locking doctrine/dbal (2.13.9)
  - Locking doctrine/deprecations (1.1.2)
  - Locking doctrine/event-manager (1.2.0)
  - Locking doctrine/inflector (2.0.8)
  - Locking doctrine/instantiator (2.0.0)
  - Locking doctrine/lexer (1.2.3)
  - Locking dragonmantank/cron-expression (v3.3.3)
  - Locking egulias/email-validator (2.1.25)
  - Locking fig/http-message-util (1.1.5)
  - Locking filp/whoops (2.15.4)
  - Locking flarum/core (v1.8.3)
  - Locking flarum/testing (v1.8.0)
  - Locking franzl/whoops-middleware (2.0.0)
  - Locking guzzlehttp/guzzle (7.8.1)
  - Locking guzzlehttp/promises (2.0.2)
  - Locking guzzlehttp/psr7 (2.6.2)
  - Locking hamcrest/hamcrest-php (v2.0.1)
  - Locking illuminate/bus (v8.83.27)
  - Locking illuminate/cache (v8.83.27)
  - Locking illuminate/collections (v8.83.27)
  - Locking illuminate/config (v8.83.27)
  - Locking illuminate/console (v8.83.27)
  - Locking illuminate/container (v8.83.27)
  - Locking illuminate/contracts (v8.83.27)
  - Locking illuminate/database (v8.83.27)
  - Locking illuminate/events (v8.83.27)
  - Locking illuminate/filesystem (v8.83.27)
  - Locking illuminate/hashing (v8.83.27)
  - Locking illuminate/macroable (v8.83.27)
  - Locking illuminate/mail (v8.83.27)
  - Locking illuminate/pipeline (v8.83.27)
  - Locking illuminate/queue (v8.83.27)
  - Locking illuminate/session (v8.83.27)
  - Locking illuminate/support (v8.83.27)
  - Locking illuminate/translation (v8.83.27)
  - Locking illuminate/validation (v8.83.27)
  - Locking illuminate/view (v8.83.27)
  - Locking intervention/image (2.7.2)
  - Locking jaybizzle/crawler-detect (v1.2.116)
  - Locking jenssegers/agent (v2.6.4)
  - Locking laminas/laminas-diactoros (2.26.0)
  - Locking laminas/laminas-escaper (2.13.0)
  - Locking laminas/laminas-httphandlerrunner (2.9.0)
  - Locking laminas/laminas-stratigility (3.11.0)
  - Locking laravel/serializable-closure (v1.3.3)
  - Locking league/commonmark (2.4.1)
  - Locking league/config (v1.2.0)
  - Locking league/flysystem (1.1.10)
  - Locking league/mime-type-detection (1.14.0)
  - Locking matthiasmullie/minify (1.3.71)
  - Locking matthiasmullie/path-converter (1.1.3)
  - Locking middlewares/base-path (v2.1.0)
  - Locking middlewares/base-path-router (v2.0.1)
  - Locking middlewares/request-handler (v2.0.2)
  - Locking middlewares/utils (v3.3.0)
  - Locking mobiledetect/mobiledetectlib (2.8.45)
  - Locking mockery/mockery (1.6.7)
  - Locking monolog/monolog (1.27.1)
  - Locking myclabs/deep-copy (1.11.1)
  - Locking nesbot/carbon (2.72.1)
  - Locking nette/schema (v1.2.5)
  - Locking nette/utils (v4.0.3)
  - Locking nikic/fast-route (v0.6.0)
  - Locking nikic/php-parser (v4.18.0)
  - Locking opis/closure (3.6.3)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.2.1)
  - Locking phpunit/php-code-coverage (9.2.29)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.6.15)
  - Locking psr/clock (1.0.0)
  - Locking psr/container (1.1.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-client (1.0.3)
  - Locking psr/http-factory (1.0.2)
  - Locking psr/http-message (1.1)
  - Locking psr/http-server-handler (1.0.2)
  - Locking psr/http-server-middleware (1.0.2)
  - Locking psr/log (1.1.4)
  - Locking psr/simple-cache (1.0.1)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking ramsey/collection (2.0.0)
  - Locking ramsey/uuid (4.7.5)
  - Locking s9e/regexp-builder (1.4.6)
  - Locking s9e/sweetdom (3.2.0)
  - Locking s9e/text-formatter (2.15.0)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.8)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.5)
  - Locking sebastian/environment (5.1.5)
  - Locking sebastian/exporter (4.0.5)
  - Locking sebastian/global-state (5.0.6)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.5)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (3.2.1)
  - Locking sebastian/version (3.0.2)
  - Locking staudenmeir/eloquent-eager-limit (v1.6.1)
  - Locking swiftmailer/swiftmailer (v6.3.0)
  - Locking sycho/codecs-base64vlq (2.0.0)
  - Locking sycho/errors (3.0.0)
  - Locking sycho/json-api (v0.5.2)
  - Locking sycho/sourcemap (2.0.0)
  - Locking symfony/config (v5.4.31)
  - Locking symfony/console (v5.4.32)
  - Locking symfony/css-selector (v6.4.0)
  - Locking symfony/deprecation-contracts (v3.4.0)
  - Locking symfony/event-dispatcher (v5.4.26)
  - Locking symfony/event-dispatcher-contracts (v3.4.0)
  - Locking symfony/filesystem (v6.4.0)
  - Locking symfony/finder (v5.4.27)
  - Locking symfony/http-foundation (v5.4.32)
  - Locking symfony/mime (v5.4.26)
  - Locking symfony/polyfill-ctype (v1.28.0)
  - Locking symfony/polyfill-iconv (v1.28.0)
  - Locking symfony/polyfill-intl-grapheme (v1.28.0)
  - Locking symfony/polyfill-intl-idn (v1.28.0)
  - Locking symfony/polyfill-intl-messageformatter (v1.28.0)
  - Locking symfony/polyfill-intl-normalizer (v1.28.0)
  - Locking symfony/polyfill-mbstring (v1.28.0)
  - Locking symfony/polyfill-php72 (v1.28.0)
  - Locking symfony/polyfill-php73 (v1.28.0)
  - Locking symfony/polyfill-php80 (v1.28.0)
  - Locking symfony/polyfill-php81 (v1.28.0)
  - Locking symfony/process (v5.4.28)
  - Locking symfony/service-contracts (v2.5.2)
  - Locking symfony/string (v6.4.0)
  - Locking symfony/translation (v5.4.31)
  - Locking symfony/translation-contracts (v2.5.2)
  - Locking symfony/yaml (v5.4.31)
  - Locking theseer/tokenizer (1.2.2)
  - Locking tijsverkoyen/css-to-inline-styles (v2.2.7)
  - Locking voku/portable-ascii (1.6.1)
  - Locking webmozart/assert (1.11.0)
  - Locking wikimedia/less.php (v3.2.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 150 installs, 0 updates, 0 removals
  - Downloading symfony/yaml (v5.4.31)
  - Downloading symfony/translation (v5.4.31)
  - Downloading symfony/string (v6.4.0)
  - Downloading symfony/console (v5.4.32)
  - Downloading symfony/filesystem (v6.4.0)
  - Downloading symfony/config (v5.4.31)
  - Downloading carbonphp/carbon-doctrine-types (1.0.0)
  - Downloading nesbot/carbon (2.72.1)
  - Downloading s9e/sweetdom (3.2.0)
  - Downloading s9e/text-formatter (2.15.0)
  - Downloading laminas/laminas-stratigility (3.11.0)
  - Downloading guzzlehttp/psr7 (2.6.2)
  - Downloading laminas/laminas-diactoros (2.26.0)
  - Downloading mobiledetect/mobiledetectlib (2.8.45)
  - Downloading symfony/http-foundation (v5.4.32)
  - Downloading ramsey/uuid (4.7.5)
  - Downloading laravel/serializable-closure (v1.3.3)
  - Downloading symfony/css-selector (v6.4.0)
  - Downloading tijsverkoyen/css-to-inline-styles (v2.2.7)
  - Downloading nette/utils (v4.0.3)
  - Downloading guzzlehttp/promises (2.0.2)
  - Downloading guzzlehttp/guzzle (7.8.1)
  - Downloading filp/whoops (2.15.4)
  - Downloading theseer/tokenizer (1.2.2)
  - Downloading nikic/php-parser (v4.18.0)
  - Downloading phpunit/phpunit (9.6.15)
  - Downloading mockery/mockery (1.6.7)
  0/27 [>---------------------------]   0%
  3/27 [===>------------------------]  11%
  7/27 [=======>--------------------]  25%
 11/27 [===========>----------------]  40%
 15/27 [===============>------------]  55%
 17/27 [=================>----------]  62%
 22/27 [======================>-----]  81%
 26/27 [==========================>-]  96%
 27/27 [============================] 100%
  - Installing axy/backtrace (2.0.0): Extracting archive
  - Installing doctrine/cache (2.2.0): Extracting archive
  - Installing doctrine/deprecations (1.1.2): Extracting archive
  - Installing doctrine/event-manager (1.2.0): Extracting archive
  - Installing doctrine/inflector (2.0.8): Extracting archive
  - Installing doctrine/lexer (1.2.3): Extracting archive
  - Installing wikimedia/less.php (v3.2.1): Extracting archive
  - Installing symfony/polyfill-ctype (v1.28.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.4.0): Extracting archive
  - Installing symfony/yaml (v5.4.31): Extracting archive
  - Installing symfony/translation-contracts (v2.5.2): Extracting archive
  - Installing symfony/polyfill-php80 (v1.28.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.28.0): Extracting archive
  - Installing symfony/translation (v5.4.31): Extracting archive
  - Installing symfony/polyfill-intl-messageformatter (v1.28.0): Extracting archive
  - Installing symfony/polyfill-php72 (v1.28.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.28.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.28.0): Extracting archive
  - Installing symfony/mime (v5.4.26): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.4.0): Extracting archive
  - Installing symfony/event-dispatcher (v5.4.26): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.28.0): Extracting archive
  - Installing symfony/string (v6.4.0): Extracting archive
  - Installing psr/container (1.1.2): Extracting archive
  - Installing symfony/service-contracts (v2.5.2): Extracting archive
  - Installing symfony/polyfill-php73 (v1.28.0): Extracting archive
  - Installing symfony/console (v5.4.32): Extracting archive
  - Installing symfony/polyfill-php81 (v1.28.0): Extracting archive
  - Installing symfony/filesystem (v6.4.0): Extracting archive
  - Installing symfony/config (v5.4.31): Extracting archive
  - Installing sycho/errors (3.0.0): Extracting archive
  - Installing sycho/codecs-base64vlq (2.0.0): Extracting archive
  - Installing sycho/sourcemap (2.0.0): Extracting archive
  - Installing sycho/json-api (v0.5.2): Extracting archive
  - Installing voku/portable-ascii (1.6.1): Extracting archive
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing carbonphp/carbon-doctrine-types (1.0.0): Extracting archive
  - Installing nesbot/carbon (2.72.1): Extracting archive
  - Installing illuminate/macroable (v8.83.27): Extracting archive
  - Installing psr/simple-cache (1.0.1): Extracting archive
  - Installing illuminate/contracts (v8.83.27): Extracting archive
  - Installing illuminate/collections (v8.83.27): Extracting archive
  - Installing illuminate/support (v8.83.27): Extracting archive
  - Installing illuminate/container (v8.83.27): Extracting archive
  - Installing illuminate/database (v8.83.27): Extracting archive
  - Installing staudenmeir/eloquent-eager-limit (v1.6.1): Extracting archive
  - Installing s9e/sweetdom (3.2.0): Extracting archive
  - Installing s9e/regexp-builder (1.4.6): Extracting archive
  - Installing s9e/text-formatter (2.15.0): Extracting archive
  - Installing psr/http-message (1.1): Extracting archive
  - Installing psr/http-server-handler (1.0.2): Extracting archive
  - Installing psr/http-server-middleware (1.0.2): Extracting archive
  - Installing nikic/fast-route (v0.6.0): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing monolog/monolog (1.27.1): Extracting archive
  - Installing psr/http-factory (1.0.2): Extracting archive
  - Installing middlewares/utils (v3.3.0): Extracting archive
  - Installing middlewares/request-handler (v2.0.2): Extracting archive
  - Installing middlewares/base-path-router (v2.0.1): Extracting archive
  - Installing middlewares/base-path (v2.1.0): Extracting archive
  - Installing matthiasmullie/path-converter (1.1.3): Extracting archive
  - Installing matthiasmullie/minify (1.3.71): Extracting archive
  - Installing league/mime-type-detection (1.14.0): Extracting archive
  - Installing league/flysystem (1.1.10): Extracting archive
  - Installing laminas/laminas-escaper (2.13.0): Extracting archive
  - Installing fig/http-message-util (1.1.5): Extracting archive
  - Installing laminas/laminas-stratigility (3.11.0): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing guzzlehttp/psr7 (2.6.2): Extracting archive
  - Installing laminas/laminas-diactoros (2.26.0): Extracting archive
  - Installing laminas/laminas-httphandlerrunner (2.9.0): Extracting archive
  - Installing mobiledetect/mobiledetectlib (2.8.45): Extracting archive
  - Installing jaybizzle/crawler-detect (v1.2.116): Extracting archive
  - Installing jenssegers/agent (v2.6.4): Extracting archive
  - Installing intervention/image (2.7.2): Extracting archive
  - Installing symfony/finder (v5.4.27): Extracting archive
  - Installing illuminate/filesystem (v8.83.27): Extracting archive
  - Installing illuminate/pipeline (v8.83.27): Extracting archive
  - Installing illuminate/bus (v8.83.27): Extracting archive
  - Installing illuminate/events (v8.83.27): Extracting archive
  - Installing illuminate/view (v8.83.27): Extracting archive
  - Installing symfony/http-foundation (v5.4.32): Extracting archive
  - Installing illuminate/translation (v8.83.27): Extracting archive
  - Installing egulias/email-validator (2.1.25): Extracting archive
  - Installing illuminate/validation (v8.83.27): Extracting archive
  - Installing illuminate/session (v8.83.27): Extracting archive
  - Installing symfony/process (v5.4.28): Extracting archive
  - Installing ramsey/collection (2.0.0): Extracting archive
  - Installing brick/math (0.11.0): Extracting archive
  - Installing ramsey/uuid (4.7.5): Extracting archive
  - Installing opis/closure (3.6.3): Extracting archive
  - Installing laravel/serializable-closure (v1.3.3): Extracting archive
  - Installing illuminate/console (v8.83.27): Extracting archive
  - Installing illuminate/queue (v8.83.27): Extracting archive
  - Installing symfony/css-selector (v6.4.0): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (v2.2.7): Extracting archive
  - Installing symfony/polyfill-iconv (v1.28.0): Extracting archive
  - Installing swiftmailer/swiftmailer (v6.3.0): Extracting archive
  - Installing nette/utils (v4.0.3): Extracting archive
  - Installing nette/schema (v1.2.5): Extracting archive
  - Installing dflydev/dot-access-data (v3.0.2): Extracting archive
  - Installing league/config (v1.2.0): Extracting archive
  - Installing league/commonmark (2.4.1): Extracting archive
  - Installing illuminate/mail (v8.83.27): Extracting archive
  - Installing illuminate/hashing (v8.83.27): Extracting archive
  - Installing illuminate/config (v8.83.27): Extracting archive
  - Installing illuminate/cache (v8.83.27): Extracting archive
  - Installing psr/http-client (1.0.3): Extracting archive
  - Installing guzzlehttp/promises (2.0.2): Extracting archive
  - Installing guzzlehttp/guzzle (7.8.1): Extracting archive
  - Installing filp/whoops (2.15.4): Extracting archive
  - Installing franzl/whoops-middleware (2.0.0): Extracting archive
  - Installing webmozart/assert (1.11.0): Extracting archive
  - Installing dragonmantank/cron-expression (v3.3.3): Extracting archive
  - Installing doctrine/dbal (2.13.9): Extracting archive
  - Installing dflydev/fig-cookies (v3.1.0): Extracting archive
  - Installing components/font-awesome (5.15.4): Extracting archive
  - Installing flarum/core (v1.8.3): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (3.2.1): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.5): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.6): Extracting archive
  - Installing sebastian/exporter (4.0.5): Extracting archive
  - Installing sebastian/environment (5.1.5): Extracting archive
  - Installing sebastian/diff (4.0.5): Extracting archive
  - Installing sebastian/comparator (4.0.8): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.2): Extracting archive
  - Installing nikic/php-parser (v4.18.0): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.29): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.1): Extracting archive
  - Installing doctrine/instantiator (2.0.0): Extracting archive
  - Installing phpunit/phpunit (9.6.15): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.6.7): Extracting archive
  - Installing flarum/testing (v1.8.0): Extracting archive
   0/150 [>---------------------------]   0%
  20/150 [===>------------------------]  13%
  30/150 [=====>----------------------]  20%
  49/150 [=========>------------------]  32%
  60/150 [===========>----------------]  40%
  77/150 [==============>-------------]  51%
  97/150 [==================>---------]  64%
 107/150 [===================>--------]  71%
 125/150 [=======================>----]  83%
 135/150 [=========================>--]  90%
 150/150 [============================] 100%
57 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating autoload files
86 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
✔ Run `yarn`? (recommended) … yes
/bin/sh: yarn: command not found

Error occurred, and could not complete:
Command failed: yarn install
/bin/sh: yarn: command not found

Error: Command failed: yarn install
/bin/sh: yarn: command not found

    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at YarnInstall.run (/usr/local/lib/node_modules/@flarum/cli/lib/steps/misc/yarn.js:12:38)
    at StepManager.runStep (/usr/local/lib/node_modules/@flarum/cli/lib/boilersmith/step-manager.js:153:45)
    at checkAndRun (/usr/local/lib/node_modules/@flarum/cli/lib/boilersmith/step-manager.js:73:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async StepManager.run (/usr/local/lib/node_modules/@flarum/cli/lib/boilersmith/step-manager.js:94:21)
    at async Init.run (/usr/local/lib/node_modules/@flarum/cli/lib/base-command.js:57:21)
    at async Init._run (/usr/local/lib/node_modules/@flarum/cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/local/lib/node_modules/@flarum/cli/node_modules/@oclif/core/lib/config/config.js:301:25)

Before the error, the following steps were completed:
- Run git init
- Generate package skeleton
- Run composer install/update`

**Comment by askvortsov1** [comment]
You should install yarn on your machine: https://yarnpkg.com/getting-started/install

Alternatively, you can use npm instead of yarn
